---
- hosts: localhost

  tasks:
  - name: create docker image using war file
    command: sudo docker build -t tomcat-webserver:latest .
    args:
      chdir: /opt/k8s

  - name: create tag to image
    command: sudo docker tag tomcat-webserver vhirewadeyar/tomcat-webserver

  - name: push image on to dockerhub
    command: sudo docker push vhirewadeyar/tomcat-webserver

  - name: remove docker images form ansible server
    command: sudo docker rmi  tomcat-webserver:latest vhirewadeyar/tomcat-webserver
    ignore_errors: yes
